version: "3.9"

services:
  web:
    build: .
    container_name: carching_whatsapp
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # useful for dev hot reload (remove in production)
    environment:
      - ENV=development
