name: Daily Sync

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call sync endpoint
        run: curl -X POST https://positive-lightly-pika.ngrok-free.app/sync