name: Daily Sync

on:
  schedule:
    - cron: '30 17 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call sync endpoint
        run: curl -s --fail -X POST https://positive-lightly-pika.ngrok-free.app/sync
